packages:
  - apps/*
  - packages/*
  - services/*

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@scarf/scarf'
  - '@swc/core'
  - ccxt
  - core-js-pure
  - esbuild
  - sharp
  - supabase
  - unrs-resolver
